# The service providing the commit statuses to GitHub.
status = [
  "buildbot/buildbot-build-script"
]

# Allow 30 minutes for builds.
timeout_sec = 1350

# Have bors delete auto-merged branches (if possible).
delete_merged_branches = true
